
[functions.create-users-from-excel]
enabled = true
verify_jwt = true
import_map = "./functions/create-users-from-excel/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-users-from-excel/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-users-from-excel/*.html" ]

[functions.get-email-from-username]
enabled = true
verify_jwt = true
import_map = "./functions/get-email-from-username/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-email-from-username/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-email-from-username/*.html" ]
